@startuml Caso uso enum

actor "ator" as ator

rectangle conteiner{
    package "pacote de alguma coisa" as pacote{
        usecase "caso De Uso" as caso
    }
}
ator .> caso: <<include>>

(outro caso) .> caso: <<include>>



@enduml