@startuml Aluno


actor "Aluno" as Aluno
note left of Aluno #LightYellow
Aluno
end note

participant "AlunoView" as AlunoView
participant "AlunoController" as AlunoController
participant "AlunoModel" as AlunoModel

ref over AlunoView, AlunoController, AlunoModel : AutenticarUsuario
Aluno -> AlunoView : ConsultarSaldo()
activate AlunoView
AlunoView ->  AlunoController : Aluno.Carteira.saldo()
activate AlunoController
AlunoController -> AlunoModel : :saldo
activate AlunoModel
AlunoModel --> AlunoController



' --> Sincrono 
' -->> Assincrono
' <-- Retorno Sincrono
' <<-- Retorno Assíncrono

@enduml