@startuml Aluno


actor "Aluno" as Aluno
note left of Aluno #LightYellow
US4
end note

participant "AlunoController" as AlunoController
participant "Componente de Negocio" as ComponenteTransacao

activate Aluno
Aluno -> TransacoesAluno : Consultar transação
activate TransacoesAluno
TransacoesAluno -> ComponenteTransacao : Consultar transações do Aluno
activate ComponenteTransacao
ComponenteTransacao -> Database : Pegar dados de transações do Aluno
Database -->> ComponenteTransacao : Transações do aluno
ComponenteTransacao -->> TransacoesAluno
deactivate ComponenteTransacao
TransacoesAluno -->> Aluno
deactivate TransacoesAluno

' --> Sincrono 
' -->> Assincrono
' <-- Retorno Sincrono
' <<-- Retorno Assíncrono

@enduml