@startuml US3


actor "Aluno" as Aluno
note left of Aluno #LightYellow
US3
end note

participant "Consultar saldo" as Tela
participant "Componente de Negocio" as Negocio
database "Banco de Dados" as Database

activate Aluno
Aluno -> Tela : Consultar saldo
activate Tela
Tela -> Negocio : Consultar saldo do Aluno
activate Negocio
Negocio -> Database : Pegar dados de saldo do Aluno
activate Database
Database -->> Negocio : Saldo do aluno
deactivate Database
Negocio -->> Tela
deactivate Negocio
Tela -->> Aluno
deactivate Tela

' --> Sincrono 
' -->> Assincrono
' <-- Retorno Sincrono
' <<-- Retorno Assíncrono

@enduml