@startuml US7


actor "Professor" as Professor
note left of Professor #LightYellow
US7
end note

participant "Enviar moedas" as Tela
participant "Componente de Negocio" as Negocio
database "Banco de Dados" as Database

Professor -> Tela : Enviar moeda
activate Tela
Tela -> Negocio : Verificar aluno
activate Negocio
Negocio -> Database : Verificar se aluno existe
activate Database
Database -->> Negocio : Aluno existe
deactivate Database
Negocio -->> Tela
deactivate Negocio
Tela -> Negocio : Enviar moeda
activate Negocio
Negocio -> Database : Salvar envio de moeda
activate Database
Database -->> Negocio
deactivate Database
Negocio -->> Tela
deactivate Negocio
Tela -->> Professor

' --> Sincrono 
' -->> Assincrono
' <-- Retorno Sincrono
' <<-- Retorno Assíncrono

@enduml
