@startuml US10


actor "Empresa" as Empresa
note left of Empresa #LightYellow
US10
end note

participant "Cadastrar vantagem" as Tela
participant "Componente de Negocio" as Negocio
database "Banco de Dados" as Database

activate Empresa
Empresa -> Tela : Inserir dados
activate Tela
Tela -> Negocio : Verificar se vantagem existe
activate Negocio
Negocio -> Database : Verifica se vantagem esta cadastrada
activate Database
Database -->> Negocio : Vantagem não esta cadastrada
deactivate Database
Negocio -->> Tela
deactivate Negocio
Tela -> Negocio : Cadastra vantagem
activate Negocio
Negocio -> Database : Salvar vantagem
activate Database
Database -->> Negocio
deactivate Database
Negocio -->> Tela
deactivate Negocio
Tela -->> Empresa
deactivate Tela

' --> Sincrono 
' -->> Assincrono
' <-- Retorno Sincrono
' <<-- Retorno Assíncrono

@enduml