@startuml US8
@startuml US8


actor "Professor" as Professor
note left of Professor #LightYellow
US8
end note

participant "Consultar saldo" as Tela
participant "Componente de Negocio" as Negocio
database "Banco de Dados" as Database

activate Professor
Professor -> Tela : Consultar saldo
activate Tela
Tela -> Negocio : Consultar saldo do Professor
activate Negocio
Negocio -> Database : Pegar dados de saldo do Professor
activate Database
Database -->> Negocio : Saldo do Professor
deactivate Database
Negocio -->> Tela
deactivate Negocio
Tela -->> Professor
deactivate Tela

' --> Sincrono 
' -->> Assincrono
' <-- Retorno Sincrono
' <<-- Retorno Assíncrono

@enduml

actor "Professor" as Professor
note left of Professor #LightYellow
US8
end note

participant "Consultar saldo" as SaldoProfessor
participant "Componente de Negocio" as ComponenteProfessor
database "Banco de Dados" as Database

activate Professor
Professor -> SaldoProfessor : Consultar saldo
activate SaldoProfessor
SaldoProfessor -> ComponenteProfessor : Consultar saldo do Professor
activate ComponenteProfessor
ComponenteProfessor -> Database : Pegar dados de saldo do Professor
activate Database
Database -->> ComponenteProfessor : Saldo do Professor
deactivate Database
ComponenteProfessor -->> SaldoProfessor
deactivate ComponenteProfessor
SaldoProfessor -->> Professor
deactivate SaldoProfessor

' --> Sincrono 
' -->> Assincrono
' <-- Retorno Sincrono
' <<-- Retorno Assíncrono

@enduml