@startuml Aluno


actor "Aluno" as Aluno
note left of Aluno #LightYellow
    Aluno
end note

participant "CarteiraAlunoView" as CarteiraAlunoView
participant "CarteiraAlunoController" as CarteiraAlunoController
participant "CarteiraAlunoModel" as CarteiraAlunoModel

group ConsultarSaldo
    ref over Aluno,CarteiraAlunoView, CarteiraAlunoController, CarteiraAlunoModel : AutenticarUsuario
    Aluno -> CarteiraAlunoView : Saldo:ConsultarSaldo()
    activate CarteiraAlunoView
    CarteiraAlunoView -> CarteiraAlunoController : CarteiraAluno.saldoTotal()
    activate CarteiraAlunoController
    CarteiraAlunoController -> CarteiraAlunoModel : getSaldo();
    activate CarteiraAlunoModel
    deactivate CarteiraAlunoModel
    deactivate CarteiraAlunoController
    deactivate CarteiraAlunoView
end

group ConsultarExtrato
    ref over Aluno,CarteiraAlunoView, CarteiraAlunoController, CarteiraAlunoModel : AutenticarUsuario
    Aluno -> CarteiraAlunoView : "Relatorio":ConsultarExtrato()
    activate CarteiraAlunoView
    CarteiraAlunoView -> CarteiraAlunoController : CarteiraAluno.gerarExtrato()
    activate CarteiraAlunoController
    CarteiraAlunoController -> CarteiraAlunoModel : List<Transacao>:findAllTransacoes()
    activate CarteiraAlunoModel
    deactivate CarteiraAlunoModel
    CarteiraAlunoController -> CarteiraAlunoController : String:relatorio()
    activate CarteiraAlunoController
    deactivate CarteiraAlunoController
    deactivate CarteiraAlunoController
    deactivate CarteiraAlunoView
end

group Transferir
    ref over Aluno,CarteiraAlunoView, CarteiraAlunoController, CarteiraAlunoModel : AutenticarUsuario
    Aluno -> CarteiraAlunoView :  Cupom:TrocarVantagem(Vantagem)
    activate CarteiraAlunoView
    CarteiraAlunoView -> CarteiraAlunoController : TrocarVantagem()
    activate CarteiraAlunoController
    CarteiraAlunoController -> CarteiraAlunoModel : ConsultarSaldo()
    activate CarteiraAlunoModel
    deactivate CarteiraAlunoModel
    CarteiraAlunoController -> CarteiraAlunoModel : ConsultarVantagem()
    activate CarteiraAlunoModel
    deactivate  CarteiraAlunoModel
    CarteiraAlunoController -> CarteiraAlunoModel : DescontarSaldo()
    activate CarteiraAlunoModel
    deactivate CarteiraAlunoModel
    CarteiraAlunoController -> CarteiraAlunoModel : GerarCupom()
    activate CarteiraAlunoModel
    deactivate CarteiraAlunoModel
    CarteiraAlunoController -->> Email : EnviarEmailCupom(Email)
    CarteiraAlunoController -->> Email : EnviarEmailConfirmacao(Email)
    deactivate CarteiraAlunoController
    deactivate CarteiraAlunoView
end





' --> Sincrono
' -->> Assincrono
' <-- Retorno Sincrono
' <<-- Retorno Assíncrono

@enduml