@startuml Aluno


actor "Aluno" as Aluno
note left of Aluno #LightYellow
    Aluno
end note

participant "CarteiraController" as CarteiraController
participant "CarteiraService" as CarteiraService
participant "CarteiraRepository" as CarteiraRepository

group ConsultarSaldo
    ref over Aluno,CarteiraController, CarteiraService, CarteiraRepository : AutenticarUsuario
    Aluno -> CarteiraController : Saldo:ConsultarSaldo()
    activate CarteiraController
    CarteiraController -> CarteiraService : CarteiraAluno.saldoTotal()
    activate CarteiraService
    CarteiraService -> CarteiraRepository : getSaldo();
    activate CarteiraRepository
    deactivate CarteiraRepository
    deactivate CarteiraService
    deactivate CarteiraController
end



group Transferir
    ref over Aluno,CarteiraController, CarteiraService, CarteiraRepository : AutenticarUsuario
    Aluno -> CarteiraController :  Cupom:TrocarVantagem(Vantagem)
    activate CarteiraController
    CarteiraController -> CarteiraService : TrocarVantagem()
    activate CarteiraService
    CarteiraService -> CarteiraRepository : ConsultarSaldo()
    activate CarteiraRepository
    deactivate CarteiraRepository
    CarteiraService -> CarteiraRepository : ConsultarVantagem()
    activate CarteiraRepository
    deactivate  CarteiraRepository
    CarteiraService -> CarteiraRepository : DescontarSaldo()
    activate CarteiraRepository
    deactivate CarteiraRepository
    CarteiraService -> CarteiraRepository : GerarCupom()
    activate CarteiraRepository
    deactivate CarteiraRepository
    CarteiraService -->> Email : EnviarEmailCupom(Email)
    CarteiraService -->> Email : EnviarEmailConfirmacao(Email)
    deactivate CarteiraService
    deactivate CarteiraController
end





' --> Sincrono
' -->> Assincrono
' <-- Retorno Sincrono
' <<-- Retorno Assíncrono

@enduml