@startuml Empresa

actor "Empresa" as Empresa
note left of Empresa #LightYellow
    Empresa
end note

participant "EmpresaView" as EmpresaView
participant "VantagemController" as VantagemController
participant "VantagemService" as VantagemService
participant "VantagemRepository" as VantagemRepository

group CadastrarVantagem
    ref over Empresa,EmpresaView, VantagemController, VantagemRepository : AutenticarUsuario
    Empresa -> EmpresaView :  CadastrarVantagem(nome, descricao, foto, custo)
    activate EmpresaView
    EmpresaView -> VantagemController : cadastrarVantagem(Vantagem)
    activate VantagemController
    VantagemController -> VantagemService : save(Vantagem)
    activate VantagemService
    VantagemService -> VantagemRepository : save(Vantagem)
    activate VantagemRepository
    deactivate VantagemRepository
    deactivate VantagemService
    deactivate VantagemController
    deactivate EmpresaView
end

@enduml
