@startuml Usuario


actor "Usuario" as Usuario
note left of Usuario #LightYellow
US4
end note

participant "UsuarioController" as UsuarioController
participant "UsuarioService" as UsuarioService
participant "UsuarioRepository" as UsuarioRepository

group AutenticacaoUsuario
    Usuario ->  UsuarioController : token<String>:logar(Usuario)
    activate UsuarioController
    UsuarioController -> UsuarioService : ValidarUsuario(Usuario.email, Usuario.senha )
    activate UsuarioService
    UsuarioService -> UsuarioRepository : UserId:Encontrado, UserPassword: Encontrada
    activate UsuarioRepository
    deactivate UsuarioRepository
    deactivate UsuarioService
    deactivate UsuarioController
end

group RegistroUsuario
    Usuario ->  UsuarioController : Usuario:cadastrar(Usuario)
    activate UsuarioController
    UsuarioController -> UsuarioService : cadastrar(Usuario.email, Usuario.senha )
    activate UsuarioService
    UsuarioService -> UsuarioRepository : Adicionar:Registrado Com Sucesso
    activate UsuarioRepository
    deactivate UsuarioRepository
    deactivate UsuarioService
    deactivate UsuarioController
end

' --> Sincrono 
' -->> Assincrono
' <-- Retorno Sincrono
' <<-- Retorno Assíncrono

@enduml