@startuml Professor

actor "Professor" as Professor
note left of Professor #LightYellow
    Professor
end note

participant "CarteiraProfessorView" as CarteiraProfessorView
participant "CarteiraProfessorController" as CarteiraProfessorController
participant "CarteiraProfessorModel" as CarteiraProfessorModel

group ConsultarSaldo
    ref over Professor,CarteiraProfessorView, CarteiraProfessorController, CarteiraProfessorModel : AutenticarUsuario
    Professor -> CarteiraProfessorView : Saldo,Extrato:ConsultarSaldo()
    activate CarteiraProfessorView
    CarteiraProfessorView -> CarteiraProfessorController : CarteiraProfessor.Carteira.saldo()
    activate CarteiraProfessorController
    CarteiraProfessorController -> CarteiraProfessorModel : Extrato:saldo
    activate CarteiraProfessorModel
    deactivate CarteiraProfessorModel
    deactivate CarteiraProfessorController
    deactivate CarteiraProfessorView
end

group Transferir
    ref over Professor,CarteiraProfessorView, CarteiraProfessorController, CarteiraProfessorModel : AutenticarUsuario
    Professor -> CarteiraProfessorView :  Cupom:TrocarVantagem(Vantagem)
    activate CarteiraProfessorView
    CarteiraProfessorView -> CarteiraProfessorController : TrocarVantagem()
    activate CarteiraProfessorController
    CarteiraProfessorController -> CarteiraProfessorModel : ConsultarSaldo()
    activate CarteiraProfessorModel
    deactivate CarteiraProfessorModel
    CarteiraProfessorController -> CarteiraProfessorModel : ConsultarVantagem()
    activate CarteiraProfessorModel
    deactivate  CarteiraProfessorModel
    CarteiraProfessorController -> CarteiraProfessorModel : GerarCupom()
    activate CarteiraProfessorModel
    deactivate CarteiraProfessorModel
    deactivate CarteiraProfessorController
    deactivate CarteiraProfessorView
end
' --> Sincrono
' -->> Assincrono
' <-- Retorno Sincrono
' <<-- Retorno Assíncrono

@enduml